name: Test Debug 9

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  TEST_VAR: ${{ github.repository }}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repo: ${{ env.TEST_VAR }}"
